#we can view the default endpoint using actuator
#and also in this file, we can specify which should be exposed
management:
  endpoints:
    web:
      exposure:
        include: '*'
#we also can have our own actuator endpoints

spring:  datasource:    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password: 248645
    driver-class-name: com.mysql.cj.jdbc.Driver

#This is for the naming in the fields. by default it full divide with underscore
#to use the phyisical naming method we use this.  jpa:    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      #ddl-auto: create-drop by using this we can use tables for temp purpose.