server:
  port: 8191
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ramsunthar/spring-cloud-config-store
          default-label: main
          search-paths:
          - 'service-config/*service'
#incase the repo is private use username and passphrase
